version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: auditing-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auditing
    ports:
      - "5432:5432"
    volumes:
      - auditing-postgres-data:/var/lib/postgresql/data

volumes:
  auditing-postgres-data:
